# Generated by Django 3.2.4 on 2021-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
